# Generated by Django 4.0.1 on 2022-01-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211119_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('O', 'User has full control of the organization and its inventory.'), ('I', "User can inspect the organization's inventory.")], default='I', max_length=1),
        ),
    ]
