# Generated by Django 4.0.1 on 2022-02-16 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_membership_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_address',
        ),
    ]
