# Generated by Django 3.1.2 on 2020-10-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201027_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'get_latest_by': 'city', 'ordering': ['city', 'street1']},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'ordering': ['role', 'organization']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'get_latest_by': 'name', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'get_latest_by': 'name', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'get_latest_by': 'name', 'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='roomnodeinstallation',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='core.node'),
        ),
        migrations.AlterField(
            model_name='roomnodeinstallation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installations', to='core.room'),
        ),
    ]
