# Generated by Django 3.1.3 on 2020-11-04 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201029_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'get_latest_by': 'device_id', 'ordering': ['device_id']},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'get_latest_by': 'timestamp_s', 'ordering': ['timestamp_s']},
        ),
    ]
