# Generated by Django 3.1.3 on 2020-11-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201109_0814'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='site',
            name='unique_site_per_organization',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='operated_by',
            new_name='operator',
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('name', 'operator'), name='unique_site_per_organization'),
        ),
    ]
