# Generated by Django 3.1.3 on 2020-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201109_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomnodeinstallation',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
