# Generated by Django 3.1.3 on 2020-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_roomnodeinstallation_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnodeinstallation',
            name='to_timestamp_s',
            field=models.PositiveIntegerField(blank=True, default=2147483647),
        ),
    ]
