# Generated by Django 3.1.3 on 2020-12-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201204_1320'),
        ('core', '0013_node_description'),
    ]

    operations = [
    ]
