# Generated by Django 3.1.4 on 2020-12-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20201204_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomnodeinstallation',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Installation Photo'),
        ),
    ]
