# Generated by Django 3.1.4 on 2020-12-11 23:13

import core.models.inventory
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20201211_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnodeinstallation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.inventory.image_filename_to_uuid, verbose_name='Installation Photo'),
        ),
    ]
