# Generated by Django 3.1.2 on 2020-10-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('trade_name', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=30)),
                ('sensor_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NodeProtocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=30, unique=True)),
                ('num_upling_msgs', models.PositiveIntegerField(default=1)),
                ('num_downlink_msgs', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
