# Generated by Django 3.1.2 on 2020-10-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=30, unique=True)),
                ('base_unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=32, unique=True)),
                ('alias', models.CharField(max_length=30)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_manager.nodemodel')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_manager.nodeprotocol')),
            ],
        ),
        migrations.AddField(
            model_name='nodemodel',
            name='quantities',
            field=models.ManyToManyField(related_name='node_models', to='device_manager.Quantity'),
        ),
    ]
