# Generated by Django 3.1.2 on 2020-10-04 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_auto_20201004_1928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeprotocol',
            old_name='num_upling_msgs',
            new_name='num_uplink_msgs',
        ),
    ]
