# Generated by Django 4.0.2 on 2022-04-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadtpuls_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stadpulssensor',
            options={'ordering': ['stadtpuls_sensor_id']},
        ),
        migrations.AddConstraint(
            model_name='stadpulssensor',
            constraint=models.UniqueConstraint(fields=('stadtpuls_sensor_id',), name='unique_statpuls_sensor'),
        ),
    ]
