# Generated by Django 3.0.10 on 2020-10-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ts_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='rel_humidity',
            new_name='rel_humidity_percent',
        ),
    ]
